name: build and test
on: [push]
jobs:
  build_and_test:
    strategy:
      fail-fast: false
    runs-on: windows-2019
    name: build and release
    steps:
    - uses: actions/checkout@v2

    - name: "dependency: boost"
      run: |
        $Url = "https://sourceforge.net/projects/boost/files/boost-binaries/1.72.0/boost_1_72_0-msvc-14.2-64.exe"
        $OutputPath = "$env:TEMP\boost.exe"
        $headers = @{ "User-Agent" = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.3" }
        Invoke-WebRequest -Uri $Url -OutFile $OutputPath -Headers $headers
        Start-Process -Wait -FilePath $OutputPath -ArgumentList "/SILENT", "/SP-", "/SUPPRESSMSGBOXES", "/DIR=C:\hostedtoolcache\windows\Boost\1.72.0\x86_64"
    - name: "dependency: boost - env variable"
      run: echo "BOOST_ROOT=C:\hostedtoolcache\windows\Boost\1.72.0\x86_64" >> $GITHUB_ENV
      shell: bash

    - name: "dependency: qt5 (windows)"
      uses: jurplel/install-qt-action@v2
      with:
        version: 5.15.1
        arch: win64_msvc2019_64

    - name: "dependency: stormlib"
      run: |
        git clone "https://github.com/ladislav-zezula/StormLib" "${{ runner.workspace }}/stormlib"
        cmake -B "${{ runner.workspace }}/stormlib/build" -S "${{ runner.workspace }}/stormlib" -DCMAKE_CXX_COMPILER=msvc2019 -DCMAKE_C_COMPILER=msvc2019 -DCMAKE_INSTALL_PREFIX="${{ runner.workspace }}/stormlib/install" -DCMAKE_BUILD_TYPE=RelWithDebInfo
        cmake --build "${{ runner.workspace }}/stormlib/build" --config RelWithDebInfo
        cmake --install "${{ runner.workspace }}/stormlib/build" --config RelWithDebInfo

    - name: "configure"
      run: cmake -Wdev -Wdeprecated --warn-uninitialized -B "${{ github.workspace }}/build" -S "${{ github.workspace }}" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_COMPILER=msvc2019 -DCMAKE_PREFIX_PATH="${{ runner.workspace }}/stormlib/install"
    - name: "build"
      run: cmake --build "${{ github.workspace }}/build" --config RelWithDebInfo
    - name: "install"
      run: cmake --install "${{ github.workspace }}/build" --prefix "${{ github.workspace }}/install" --config RelWithDebInfo

    - run: |
        mkdir dependencies/
        cp -av "${{ env.Qt5_Dir }}/bin/"*"dll" dependencies/
      shell: bash
    - run: |
        mkdir dependencies/plugins/
        cp -av "${{ env.QT_PLUGIN_PATH }}/" dependencies/
      shell: bash

    - uses: vimtor/action-zip@v1
      with:
        dest: noggit-windows-2019-msvc2019-dependencies-${{ github.sha }}.zip
        files: dependencies/
    - uses: actions/upload-artifact@v4
      with:
        name: windows-2019-msvc2019-dependencies
        path: noggit-windows-2019-msvc2019-dependencies-${{ github.sha }}.zip

    - uses: vimtor/action-zip@v1
      with:
        dest: noggit-windows-2019-msvc2019-${{ github.sha }}.zip
        files: install
    - uses: actions/upload-artifact@v4
      with:
        name: windows-2019-msvc2019
        path: noggit-windows-2019-msvc2019-${{ github.sha }}.zip
